# Generated by Django 4.0.3 on 2022-06-03 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=255)),
                ('desription', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cu_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('cm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Model_details',
            fields=[
                ('mid', models.IntegerField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.maker')),
            ],
        ),
        migrations.CreateModel(
            name='Car_maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.car')),
                ('maker_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.maker')),
            ],
        ),
        migrations.CreateModel(
            name='Car_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.car')),
                ('cu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.customer')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.model_details'),
        ),
    ]
